import {
  Mail,
  Phone,
  MapPin,
  User,
  ShoppingBag,
  Heart,
  Star,
  CreditCard,
  LogOut,
  Camera,
  Settings,
  Bell,
  Save,
  Trash,
  Edit,
  Check,
  Plus,
  Lock,
  Sun,
  Moon,
  ShoppingCart,
  CheckCircle2,
  Banknote,
  Truck,
  PackageCheck,
  Clock,
  BadgeCheck,
  CircleX,
  Ban,
  Loader2,
  TriangleAlert,
  ChevronRight,
  DollarSign,
  Users,
  Package,
  TrendingUp,
  CheckCircle,
  XCircle,
  Eye,
  MoreHorizontal,
  ArrowUpRight,
  Search,
  Circle,
  ChevronDown,
  PanelLeft,
  AlertTriangle,
  PoundSterling,
  Euro,
  Trash2,
} from "lucide-react";

export const iconMap = {
  mail: Mail,
  phone: Phone,
  location: MapPin,
  user: User,
  orders: ShoppingBag,
  cart: ShoppingCart,
  wishlist: Heart,
  reviews: Star,
  payment: CreditCard,
  logout: LogOut,
  camera: Camera,
  settings: Settings,
  notifications: Bell,
  save: Save,
  trash: Trash,
  edit: Edit,
  check: Check,
  plus: Plus,
  password: Lock,
  sun: Sun,
  moon: Moon,
  checkCircle2: CheckCircle2,
  creditCard: CreditCard,
  banknote: Banknote,
  truck: Truck,
  packageCheck: PackageCheck,
  clock: Clock,
  badgeCheck: BadgeCheck,
  circleX: CircleX,
  ban: Ban,
  loader: Loader2,
  triangleAlert: TriangleAlert,
  chevronRight: ChevronRight,
  dollarSign: DollarSign,
  users: Users,
  package: Package,
  trendingUp: TrendingUp,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  eye: Eye,
  moreHorizontal: MoreHorizontal,
  arrowUpRight: ArrowUpRight,
  search: Search,
  circle: Circle,
  chevronDown: ChevronDown,
  panelLeft: PanelLeft,
  alertTriangle: AlertTriangle,
  poundSterling: PoundSterling,
  euro: Euro,
  trash2: Trash2,
};
